version: '3'

services:
  nginx:
    image: nginx:stable
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  processes:
    build: processes-api/.
    environment:
      - SCRIPT_NAME=/api
    volumes:
      - ./processes-api/config.yml:/pygeoapi/local.config.yml
      - ./processes-api/data/test.geojson:/pygeoapi/data/test.geojson
      - ./processes-api/model1/:/pygeoapi/pygeoapi/process/
      - ./processes-api/plugin.py:/pygeoapi/pygeoapi/plugin.py
