version: "3"

services:
  nginx:
    image: nginx:stable
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  api:
    build: api/.
    environment:
      - LOGLEVEL=DEBUG
      - FLASK_DEBUG=True
      - POSTGRES_USER=cut_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cut_dev
    ports:
      - 5002:5002
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - postgis
      - nginx

  frontend:
    build: frontend/.
    depends_on:
      - nginx
    working_dir: /home/node/workspace
    user: node
    command: "npm start"
    volumes:
      - ./frontend:/home/node/workspace

  geoserver:
    image: kartoza/geoserver
    depends_on:
      - postgis
    ports:
      - 8080:8080
    volumes:
      - ./geoserver/data/geoserver:/opt/geoserver/data_dir
    env_file:
      - ./geoserver/configs/geoserver
    networks:
      - backend

  postgis:
    container_name: "postgis"
    image: postgis/postgis
    ports:
      - 5432:5432
    volumes:
      - ./api/initializers/db:/docker-entrypoint-initdb.d:delegated
      - ./geoserver/data/pg_data:/var/lib/postgresql/data
    env_file:
      - ./geoserver/configs/postgis
    networks:
      - backend

networks:
  backend:
