version: '3'

services:
  nginx:
    image: nginx:stable
    ports:
      - "3000:80"
      - "3001:3001"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  frontend:
    image: node:18
    working_dir: /home/node/workspace
    user: node
    command: "npm start"
    depends_on:
      - nginx
    expose:
      - 3000
      - 3001
    volumes:
      - ./frontend:/home/node/workspace
